<link rel="shortcut icon" href="Content/Images/favicon.ico"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta http-equiv="refresh" content="900">
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link href="Content/Css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="Content/Js/jquery.min.js"></script>
<script src="Content/Js/bootstrap.min.js"></script>
<!-- Webpage Hide Code Ctrl+U,F12 And Right Click HTML -->
<script src="Content/Js/disabledRightClickAndCtrl.js"></script>
<!-- css -->
<link href="Content/Css/button.css" rel="stylesheet" type="text/css" />
<link href="Content/Css/textbox.css" rel="stylesheet" type="text/css" />
<link href="Content/Css/calendar.css" rel="stylesheet" type="text/css" />
<link href="Content/Css/textcolor.css" rel="stylesheet" type="text/css" />
<link href="Content/Css/responsive.css" rel="stylesheet" type="text/css" />
<link href="Content/Css/font-awesome.min.css" rel="stylesheet" type="text/css" />
 <!--datepicker-->
<link href="Content/Css/jquery-ui.css" rel="stylesheet" type="text/css" />	
<script src="Content/Js/jquery-1.12.4.js"></script>
<script src="Content/Js/jquery-ui.js"></script>
<!--SWEAT ALERT-->
<script src="Content/Js/sweetalert.js"></script>
<!--Jquery BlockUI-->
<script src="Content/Js/jquery.blockUI.js"></script>
